[build]
  command = "npm run build"
  publish = "dist/public"

# SPA fallback so client-side routing works on refresh/deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: proxy API requests to your backend (uncomment and set your URL)
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR-BACKEND-HOST/api/:splat"
#   status = 200
#   force = true
